name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - uses: actions/checkout@v2
    - name: Build the PHP 8.1 Docker image
      run: docker build . --file 8/8.1/Dockerfile.apache --tag ianmgg/php81:latest
    - name: Push PHP 8.1 latest
      run: docker push ianmgg/php81:latest
    - name: Build the PHP 8.1 dev Docker image
      run: docker build . --file 8/8.1/Dockerfile.apache.dev --tag ianmgg/php81:dev
    - name: Push PHP 8.1 dev
      run: docker push ianmgg/php81:dev
    - name: Build the PHP 8.1 cli Docker image
      run: docker build . --file 8/8.1/Dockerfile.cli --tag ianmgg/php81:cli
    - name: Push PHP 8.1 cli
      run: docker push ianmgg/php81:cli
    - name: Build the PHP 8.0 Docker image
      run: docker build . --file 8/8.0/Dockerfile.apache --tag ianmgg/php80:latest
    - name: Push PHP 8.0 latest
      run: docker push ianmgg/php80:latest
    - name: Build the PHP 8.0 dev Docker image
      run: docker build . --file 8/8.0/Dockerfile.apache.dev --tag ianmgg/php80:dev
    - name: Push PHP 8.0 dev
      run: docker push ianmgg/php80:dev
    - name: Build the PHP 8.0 cli Docker image
      run: docker build . --file 8/8.0/Dockerfile.cli --tag ianmgg/php80:cli
    - name: Push PHP 8.0 cli
      run: docker push ianmgg/php80:cli
    - name: Build the PHP 7.4 Docker image
      run: docker build . --file 7/7.4/Dockerfile.apache --tag ianmgg/php74:latest
    - name: Push PHP 7.4 latest
      run: docker push ianmgg/php74:latest
    - name: Build the PHP 7.4 dev Docker image
      run: docker build . --file 7/7.4/Dockerfile.apache.dev --tag ianmgg/php74:dev
    - name: Push PHP 7.4 dev
      run: docker push ianmgg/php74:dev
    - name: Build the PHP 7.4 cli Docker image
      run: docker build . --file 7/7.4/Dockerfile.cli --tag ianmgg/php74:cli
    - name: Push PHP 7.4 cli
      run: docker push ianmgg/php74:cli
