name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
  repository_dispatch:
    types: [build-docker]

jobs:
  build_apache:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php_version: ['8.2', '8.1', '8.0']
    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - uses: actions/checkout@v2
    - name: Build the Apache Docker image
      run: docker build . --file 8/${{ matrix.php_version }}/Dockerfile.apache --tag ianmgg/php${{ matrix.php_version }}:latest
    - name: Push Apache Docker image
      run: docker push ianmgg/php${{ matrix.php_version }}:latest

  build_cli:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php_version: ['8.2', '8.1', '8.0']
    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - uses: actions/checkout@v2
    - name: Build the CLI Docker image
      run: docker build . --file 8/${{ matrix.php_version }}/Dockerfile.cli --tag ianmgg/php${{ matrix.php_version }}:cli
    - name: Push CLI Docker image
      run: docker push ianmgg/php${{ matrix.php_version }}:cli

  build_dev:
    needs: build_apache
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php_version: ['8.2', '8.1', '8.0']
    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - uses: actions/checkout@v2
    - name: Build the Dev Docker image
      run: docker build . --file 8/${{ matrix.php_version }}/Dockerfile.apache.dev --tag ianmgg/php${{ matrix.php_version }}:dev
    - name: Push Dev Docker image
      run: docker push ianmgg/php${{ matrix.php_version }}:dev
