name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
  repository_dispatch:
    types: [build-docker]

jobs:
  # Build apache and cli images in parallel
  build_apache_and_cli:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php_version: ['8.3', '8.2', '8.1']
        config: 
          - {dockerfile_suffix: 'apache', tag_suffix: 'latest'}
          - {dockerfile_suffix: 'cli', tag_suffix: 'cli'}
    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      with:
        platforms: linux/amd64,linux/arm64
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - uses: actions/checkout@v4
    - name: Set TAG_VERSION
      run: |
        TAG_VERSION=${{ matrix.php_version }} 
        echo "TAG_VERSION=${TAG_VERSION//./}" >> $GITHUB_ENV
    - name: Build and Push the Docker image
      run: |
        docker buildx build . \
          --platform linux/amd64,linux/arm64 \
          --file 8/${{ matrix.php_version }}/Dockerfile.${{ matrix.config.dockerfile_suffix }} \
          --tag ianmgg/php$TAG_VERSION:${{ matrix.config.tag_suffix }} \
          --push
 
  # Build dev image which depends on apache image
  build_dev:
    needs: build_apache_and_cli
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php_version: ['8.3', '8.2', '8.1']
    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      with:
        platforms: linux/amd64,linux/arm64
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - uses: actions/checkout@v4
    - name: Set TAG_VERSION
      run: |
        TAG_VERSION=${{ matrix.php_version }}
        echo "TAG_VERSION=${TAG_VERSION//./}" >> $GITHUB_ENV
    - name: Build and Push the Docker image
      run: |
        docker buildx build . \
          --platform linux/amd64,linux/arm64 \
          --file 8/${{ matrix.php_version }}/Dockerfile.apache.dev \
          --tag ianmgg/php$TAG_VERSION:dev \
          --push