name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
  repository_dispatch:
    types: [build-docker]

jobs:

  # Build apache and cli images in parallel
  build_apache_and_cli:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php_version: ['8.3', '8.2', '8.1', '8.0']
        config: 
          - {dockerfile_suffix: 'apache', tag_suffix: 'latest'}
          - {dockerfile_suffix: 'cli', tag_suffix: 'cli'}
    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        TAG_VERSION=${{ matrix.php_version }} # e.g. 8.1
        TAG_VERSION=${TAG_VERSION//./} # e.g. 81
        docker build . --file 8/${{ matrix.php_version }}/Dockerfile.${{ matrix.config.dockerfile_suffix }} --tag ianmgg/php$TAG_VERSION:${{ matrix.config.tag_suffix }}
    - name: Push Docker image
      run: |
        TAG_VERSION=${{ matrix.php_version }} # e.g. 8.1
        TAG_VERSION=${TAG_VERSION//./} # e.g. 81
        docker push ianmgg/php$TAG_VERSION:${{ matrix.config.tag_suffix }}

  # Build dev image which depends on apache image
  build_dev:
    needs: build_apache_and_cli
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php_version: ['8.3', '8.2', '8.1', '8.0']
    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        TAG_VERSION=${{ matrix.php_version }} # e.g. 8.1
        TAG_VERSION=${TAG_VERSION//./} # e.g. 81
        docker build . --file 8/${{ matrix.php_version }}/Dockerfile.apache.dev --tag ianmgg/php$TAG_VERSION:dev
    - name: Push Docker image
      run: |
        TAG_VERSION=${{ matrix.php_version }} # e.g. 8.1
        TAG_VERSION=${TAG_VERSION//./} # e.g. 81
        docker push ianmgg/php$TAG_VERSION:dev
