name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
  repository_dispatch:
    types: [build-docker]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php_version: ['8.2', '8.1', '8.0']
        config: 
          - {dockerfile_suffix: 'apache', tag_suffix: 'latest'}
          - {dockerfile_suffix: 'apache.dev', tag_suffix: 'dev'}
          - {dockerfile_suffix: 'cli', tag_suffix: 'cli'}
    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file 8/${{ matrix.php_version }}/Dockerfile.${{ matrix.config.dockerfile_suffix }} --tag ianmgg/php${{ matrix.php_version }}:${{ matrix.config.tag_suffix }}
    - name: Push Docker image
      run: docker push ianmgg/php${{ matrix.php_version }}:${{ matrix.config.tag_suffix }}
